name: Run Custom JMeter Tests
on:
  push:
    branches:
      - main
jobs:
  jmeter:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up JMeter
        run: |
          # Install JMeter (if not already installed)
          # Set up any other prerequisites
      - name: Run JMeter Tests
        run: |
          cd $GITHUB_WORKSPACE/path/to/apache-jmeter-5.6.3/apache-jmeter-5.6.3/bin
          ./jmeter -n -t tests/Example-Demo.jmx -l reports/result.jtl
