name: JMeter Tests

# Controls when the action is run
on:
# Triggers the workflow on push or pull requests but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
#   This workflow contains a single job called "build"
  build:
# The type of runner that the job will run on - Github Hosted or Self-Hosted (Windows/Linux/MacOS)
    runs-on: windows-latest
# Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
# Checks out your repository so your job can access it
        uses: actions/checkout@v2
      - name: where are the files?
        run: |
           pwd
           ls
      - name: create test_report
        run: |
           mkdir $GITHUB_WORKSPACE/test_report
# Install Jmeter, OpenJDK
      - name: Set up JMeter
        run: |
          choco install jmeter -y
      - name: Run JMeter test
        run: |
          cd $GITHUB_WORKSPACE
          for i in $( ls -A1 *.jmx); do
            cd $GITHUB_WORKSPACE/apache-jmeter-5.4.1/bin
            mkdir $GITHUB_WORKSPACE/test_report/${i%.jmx}
            jmeter -n -t $GITHUB_WORKSPACE/$i  -l $GITHUB_WORKSPACE/${i%.jmx}.jtl -e -o $GITHUB_WORKSPACE/test_report/${i%.jmx}
          done
      - name: move jtl files to test_report
        run: |
         move *.jtl $GITHUB_WORKSPACE/test_report
      - name: Upload JMeter Test Results
        uses: actions/upload-artifact@v2.2.4
        with:
         name: test_results
         path: test_report
