name: Example-Demo JMeter Test and Report

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create test_report directory
        run: mkdir $GITHUB_WORKSPACE/test_report

      - name: Install JMeter
        run: |
          choco install openjdk
          java -version
          wget https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.4.1.zip
          Expand-Archive -Path apache-jmeter-5.4.1.zip -DestinationPath .

      - name: Install JMeter plugins
        run: |
          cd $GITHUB_WORKSPACE/apache-jmeter-5.4.1
          wget -q --no-check-certificate https://jmeter-plugins.org/files/packages/jpgc-dummy-0.4.zip
          Expand-Archive -Path jpgc-dummy-0.4.zip -DestinationPath .

      - name: Run JMeter scripts
        run: |
          cd $GITHUB_WORKSPACE
          for i in $(ls -A1 *.jmx); do
            mkdir $GITHUB_WORKSPACE/test_report/${i%.jmx}
            ./apache-jmeter-5.4.1/bin/jmeter -n -t $i -e -o $GITHUB_WORKSPACE/test_report/${i%.jmx}/html
          done

      - name: Upload JMeter Test Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-reports
          path: $GITHUB_WORKSPACE/test_report
